sonar.projectKey=EZFood-API
sonar.projectName=EZFood API
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.js
sonar.host.url=http://localhost:9000
sonar.token=sqp_46f796a96423040ad0ae7eb42cc6d0f4ac989f94